apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-deployment
  namespace: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - name: nexus-container
        image: sonatype/nexus3
        ports:
        - containerPort: 8081