version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - /data/prometheus/install-docker/volumes/grafana/data:/var/lib/grafana
    restart: unless-stopped