# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

VAGRANT_BOX         = "generic/centos8s"
VAGRANT_BOX_VERSION = "4.3.4"
CPUS_WORKER_NODE    = 2
MEMORY_WORKER_NODE  = 2048
WORKER_NODES_COUNT  = 3


Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  
  # Kubernetes Worker Nodes
  (1..WORKER_NODES_COUNT).each do |i|

    config.vm.define "kafkanode#{i}" do |node|

      node.vm.box               = VAGRANT_BOX
      node.vm.box_check_update  = false
      node.vm.box_version       = VAGRANT_BOX_VERSION
      node.vm.hostname          = "kafkanode#{i}.eai.com"

      node.vm.network "private_network", ip: "172.16.16.11#{i}"

      node.vm.provider :virtualbox do |v|
        v.name    = "kafkanode#{i}"
        v.memory  = MEMORY_WORKER_NODE
        v.cpus    = CPUS_WORKER_NODE
      end

      node.vm.provider :libvirt do |v|
        v.memory  = MEMORY_WORKER_NODE
        v.nested  = true
        v.cpus    = CPUS_WORKER_NODE
      end
      
    end

  end

end
