# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

VAGRANT_BOX         = "generic/centos8s"
VAGRANT_BOX_VERSION = "4.3.4"
CPUS_TERRAFORM_NODE    = 2
MEMORY_TERRAFORM_NODE  = 4096


Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  # Kubernetes Master Server
  config.vm.define "terraform-node" do |node|
  
    node.vm.box               = VAGRANT_BOX
    node.vm.box_check_update  = false
    node.vm.box_version       = VAGRANT_BOX_VERSION
    node.vm.hostname          = "terraform-node.eai.com"

    node.vm.network "private_network", ip: "172.16.16.10"
    # node.vm.network "public_network", bridge: "Realtek PCIe GbE Family Controller"
  
    node.vm.provider :virtualbox do |v|
      v.name    = "terraform-node"
      v.memory  = MEMORY_TERRAFORM_NODE
      v.cpus    = CPUS_TERRAFORM_NODE
    end
  
    node.vm.provider :libvirt do |v|
      v.memory  = MEMORY_TERRAFORM_NODE
      v.nested  = true
      v.cpus    = CPUS_TERRAFORM_NODE
    end
end
end
