# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

VAGRANT_BOX         = "generic/ubuntu2204"
VAGRANT_BOX_VERSION = "4.2.10"
DOCKERS_MEMORY = 2048
DOCKERS_CPUS = 2
ANSIBLE_MEMORY = 2048
ANSIBLE_CPUS = 2


Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "scripts/bootstrap.sh"

    # Provision Jenkins server
    config.vm.define "dockerrepo" do |dockerrepo|
      dockerrepo.vm.box = VAGRANT_BOX
      dockerrepo.vm.box_check_update = false
      dockerrepo.vm.box_version = VAGRANT_BOX_VERSION
      dockerrepo.vm.hostname = "docker.example.com"
      
      dockerrepo.vm.network "private_network", ip: "172.16.16.201"
      
      dockerrepo.vm.provider :virtualbox do |v|
          v.name = "dockerrepo"
          v.memory = DOCKERS_MEMORY
          v.cpus = DOCKERS_CPUS
        end
      
        dockerrepo.vm.provider :libvirt do |v|
          v.memory = DOCKERS_MEMORY
          v.nested = true
          v.cpus = DOCKERS_CPUS
        end
      
        dockerrepo.vm.provision "shell", path: "scripts/bootstrap_dockers.sh"
    end
    
end