import http from 'k6/http';
import { sleep } from 'k6';


function generateUniqueTransactionID(vuNumber) {
    const randomPart = Math.floor(Math.random() * 1000000); 
    const uniqueTransactionID = `${vuNumber}_${randomPart}`;
    return uniqueTransactionID;
}

export let options = {
    vus: 10,
    duration: '5s',
};

export default function () {

    const vuNumber = __VU;

    const uniqueTransactionID = generateUniqueTransactionID(vuNumber);
    console.log(uniqueTransactionID);

    
    const apiEndpoint = 'http://172.30.6.77:3002/trigger-job';

    const apiHeaders = {
        'Content-Type': 'application/json',
        
    };

    const postData = {
        "header": {
            "TellerNum": "2542",
            "BrchNum": "999",
            "Uid": uniqueTransactionID
        },
        "data": {
            "CustNumber": "100011019851",
            "CustGrp": "01",
            "RelnshpMgr": "0",
            "TitleCode": "1",
            "FirstName": "KAZI  ZUBAIR  AHMED",
            "LastName": "",
            "BussName": "",
            "ThrsldAmt": "0",
            "AddrLine1": "62/6, SHANTINAGAR,PALTAN PLAZA,FLAT-1/E",
            "AddrLine2": "Purana Paltan Lane",
            "AddrLine3": "302665",
            "AddrLine4": "JHALOKATHI",
            "Dmcle": "BD",
            "HomePhnNum": "01712860961",
            "FaxNum": "",
            "BussPhnNum": "01712860962",
            "MobileNum": "01712860961",
            "Natlty": "BD",
            "OccupCode": "",
            "LangCode": "01",
            "IdNum": "2696536123087",
            "IdIssueDt": "01012010",
            "IdIssuedAt": "BD",
            "IdTyp": "51",
            "DmstcRisk": "ZZ",
            "CrossBrdrRisk": "ZZ",
            "VipCode": "0",
            "BrkrStat": "000",
            "SegCode": "",
            "LckrHldr": "",
            "TFNInd": "0",
            "HomeBrchNum": "6",
            "CustLmt": "",
            "CustParentLmtInd": "",
            "IndustLmtInd": "",
            "CountryLmtInd": "",
            "Yesno5": "",
            "Comdty": "",
            "Risk": "02",
            "GrpID": "99999",
            "BussSecCode": "00053",
            "CustMidName": "",
            "FatherName": "KAZI  ZAHIRUDDIN  BABAR",
            "MotherMaidenName": "KAZI  ZAHIDA  AHMED",
            "RelativeInd": "F",
            "ResdncyStat": "1",
            "CisOrgCode": "",
            "BsrOrgCode": "ZZ",
            "DtOfBirth": "30091983",
            "GndrCode": "M",
            "MaritalStat": "",
            "EstDt": "",
            "StrtDt": "",
            "CustTyp": "0104",
            "VisaIssueBy": "",
            "VisaIssueDt": "",
            "VisaExpryDt": "",
            "VisaDetail": "",
            "LiquidDt": "",
            "PermanentReturnDt": "",
            "NPATrade": "",
            "NPANonTrade": "",
            "TradeCust": "",
            "CountryOfRes": "BD",
            "CustState": "001",
            "CityBus": "001",
            "IncomeTaxPan": "413786514597",
            "VoterID": "00000000000000000000",
            "ApplyTDS": "",
            "IdIssueRmrk": "",
            "CustEvaluationReq": "",
            "GreetingReqd": "0",
            "IdTyp1": "07",
            "IdNum1": "413786514597",
            "Tbd": "",
            "Tbd1": "",
            "Tbd2": "",
            "Email": "",
            "DfltStr501": "0",
            "FundMgmtUnit": "0",
            "PrevOccupationalCode": "0053",
            "Caste": "004",
            "IncomeRange": "01",
            "CustRisk": "09",
            "WealthMgmtInd": "",
            "Flag1": "Y",
            "Flag2": "",
            "Flag3": "",
            "Flag4": "",
            "Flag5": "N",
            "Attr1": "",
            "Attr2": "",
            "Attr3": "",
            "Attr4": "",
            "Attr5": "",
            "Attr6": "",
            "Attr7": "01712860961",
            "Attr8": "",
            "Attr9": "",
            "Attr10": "Service",
            "TrsrySrvc": "N",
            "ExmptnProfile": "0",
            "TradeRepository": "",
            "TradeGold": "",
            "BussNum": "",
            "CoName": "",
            "PlceOfIncorp": "",
            "Addr1": "",
            "Addr2": "",
            "Addr3": "",
            "PhnNum": "0",
            "FaxNum1": "0",
            "CoWebsite": "",
            "ContactName1": "",
            "ContactName2": "",
            "ContactTitle1": "00",
            "ContactTitle2": "00",
            "TradeLicenceNum": "0",
            "AddrProofDt": "",
            "IdExpDt": "01012030",
            "CustCat": "R",
            "StaffNum": "0",
            "KYCDt": "30062022",
            "ContactNum1": "0",
            "ContctNum2": "0",
            "CorpGroupID": "",
            "PrefixAmendSpouse": "",
            "PrefixAmendFather": "",
            "PrefixAmendMother": "",
            "PrefixNonIndAmmend": "",
            "CustomerName": "KAZI  ZUBAIR  AHMED",
            "Postcd": "",
            "Postcdca": "1217",
            "Postcdra": "",
            "Postcdpa": "",
            "Postcdoa": "",
            "Postcdec": "",
            "StatNum": "",
            "USResdncy": "",
            "POAByUSCtzn": "",
            "TaxedWthUSPerson": "",
            "UsID": "",
            "IdNum2": "",
            "DtOfIssue": "",
            "CountryOfBirth": "BD",
            "SrvcTaxExempt": "N",
            "CountryOfTaxRsdnc": "BD",
            "TinIssueCountry": "",
            "Rmrk": "",
            "ExclusionCat": "",
            "EntityLstngStat": "",
            "OtherXchgForEntity": "",
            "RelatedEntityLstngStat": "",
            "OtherXchgForRelatedEntity": "",
            "RelatedEntityName": "",
            "NfEntityTyp": "",
            "TypOfFI": "",
            "TypOfRptgFI": "",
            "GiinStat": "",
            "GIIN": "",
            "ExmptnCat": "",
            "NameOfSponsorngEntity": "",
            "Addr4": "",
            "Addr5": "",
            "Addr6": "",
            "Addr7": "",
            "CountryOfAddr": "",
            "USID1": "",
            "IdNum3": "",
            "TinIssueCountry2": "",
            "UsID1": "",
            "IdNum4": "",
            "TinIssueCountry3": "",
            "UsID2": "",
            "IdNum5": "",
            "TinIssueCountry4": "",
            "UsID3": "",
            "IdNum6": "",
            "TinIssueCountry5": "",
            "CaptureProprietor": "N",
            "DtOfEst": "",
            "Bank1": "",
            "Brch1": "",
            "OvrAllLmt1": "0.000",
            "Bank2": "",
            "Brch2": "",
            "OvrAllLmt2": "0.000",
            "Bank3": "",
            "Brch3": "",
            "OvrAllLmt3": "0.000",
            "Bank4": "",
            "Brch4": "",
            "OvrAllLmt4": "0.000",
            "Bank5": "",
            "Brch5": "",
            "OvrAllLmt5": "0.000",
            "PanName": "",
            "DisblFlag": "N",
            "CountryOfResOffc": "",
            "State1Offc": "",
            "CityCodeOffc": "",
            "PstCodeOffc": "0",
            "Distt": "",
            "FiInd": "",
            "IntlTradeTrnovr": "",
            "MinorToMajorKYC": "",
            "InsuTyp": "",
            "GrpInsNum1": "",
            "GrpInsNum2": "",
            "ExpDt": "",
            "Community": "06",
            "IssueAuthty": "Election Commision, Bangladesh",
            "IrcLmt": "0.000",
            "IrcUtility": "0.000",
            "NameEmg": "",
            "Addr8": "62/6, SHANTINAGAR,PALTAN PLAZA,FLAT-1/E",
            "Addr9": "",
            "Divis": "",
            "DisttCode": "",
            "MadeInIndia": "",
            "OfcAddr": "",
            "CountryEmg": "BD",
            "EmailEmg": "",
            "RelationEmg": "01",
            "MoblieEmg": "0",
            "ShrtName": "",
            "PrfxAmend": "KAZI",
            "SpouseName": "",
            "CustRiskImp": "03",
            "CounRiskImp": "03",
            "IccdRisk": "",
            "ReguLike": "",
            "ReguImp": "",
            "EnivRisk": "03",
            "PhnExtn1": "",
            "PhoneIm1": "",
            "Thana1": "054",
            "SubOffice1": "00241",
            "EmpCode": "",
            "Addr10": "62/6, SHANTINAGAR,PALTAN PLAZA,FLAT-1/E",
            "Addr11": "Purana Palatan Lane",
            "Addr12": "302665",
            "Addr13": "",
            "StateCode1": "001",
            "CityCode1": "001",
            "CountryTemp": "BD",
            "Thana2": "054",
            "SubOfc2": "00241",
            "PhnRsdnc1": "01712860961",
            "PhnBus1": "01712860961",
            "PhnExtn2": "000000000000",
            "PhnIm2": "000000000000",
            "FaxNum2": "0",
            "TellexNum1": "01712860961",
            "Email1": "zubair@jamunabank.com.bd",
            "EffDt1": "",
            "ExpryDt1": "",
            "Addr14": "",
            "Addr15": "",
            "Addr16": "",
            "Addr17": "",
            "StateCode2": "",
            "CityCode2": "",
            "CountryCode2": "BD",
            "Thana3": "",
            "SubOfc3": "",
            "PhnRsdnc2": "",
            "PhnBus2": "",
            "PhnExtn3": "",
            "PhoneIm3": "",
            "FaxNum3": "0",
            "TellexNum2": "0",
            "Email2": "",
            "EffDt2": "",
            "ExpryDt2": "",
            "Addr18": "",
            "Addr19": "",
            "Addr20": "",
            "Addr21": "",
            "StateCode3": "001",
            "CityCode3": "",
            "CountryCode3": "BD",
            "Thana4": "",
            "SubOfc4": "",
            "PhnRsdnc3": "01712860961",
            "PhnBus3": "01712860961",
            "PhnExtn4": "",
            "PhnIm4": "",
            "FaxNum4": "0",
            "TellexNum3": "0",
            "Email3": "",
            "EffDt3": "01012020",
            "ExpryDt3": "01012023",
            "Addr22": "",
            "Addr23": "",
            "Addr24": "",
            "Addr25": "",
            "StateCode4": "",
            "CityCode4": "",
            "CountryCode4": "BD",
            "Thana5": "",
            "SubOfc5": "",
            "PhnRsdnc4": "",
            "PhnBus4": "",
            "PhnExtn5": "",
            "PhoneIm5": "",
            "FaxNum5": "0",
            "TellexNum4": "0",
            "Email4": "",
            "EffDt4": "",
            "ExpryDt4": "",
            "NetWorth": "0.000",
            "FixedAsset": "0.000",
            "Resource": "",
            "NatureBus": "",
            "PrimTyp1": "02",
            "SeconTyp1": "03",
            "PrimTyp2": "012390",
            "SecndryTyp2": "012390",
            "FnlSec": "915059",
            "Relcusm": "",
            "VerifyOff": "",
            "Designation": "16",
            "Tit1": "01",
            "Tit2": "01",
            "Tit3": "02",
            "DisttBirth": "001",
            "DisttBirth1": "DHAKA",
            "TypProd": "",
            "Manpower1": "0",
            "Manpower2": "0",
            "BussInfo": "",
            "PreOccup": "0053",
            "RelpShell": "",
            "SocialNet": "",
            "EduStat": "",
            "Natlty2": "",
            "Natlty3": "",
            "ArrivalDt": "",
            "NetAsset": "0",
            "SmeTyp": "05",
            "BankNbfi": "",
            "BankNm": "",
            "ErcNum1": "0006023038",
            "IrcNum1": "00000000000000000000000000000000000000000000000000",
            "ErcExpryDt": "01012023",
            "IrcExpryDt": "01012023",
            "FixedAssetExcl": "0.000",
            "ProofAddrTyp": "",
            "ProfCenter": "",
            "CustBehaviour": "",
            "RefNum": "",
            "EpvalUnit": "",
            "EpzName": "",
            "ForeignInvest": "",
            "PermanentAddLandLine": "+88",
            "PermanentAddMobile": "+88",
            "PermanentAddFax": "+88",
            "CorrAddLandLine": "+88",
            "CorrAddMobile": "+88",
            "CorrAddFax": "+88",
            "RgstrAddrLandLine": "+88",
            "RgstrAddrMobile": "+88",
            "RgstrAddrFax": "+88",
            "ProfAddLandLine": "+88",
            "ProfAddrMobile": "+88",
            "ProfAddrFax": "+88",
            "OtherAddrLan": "+88",
            "OtherAddrMob": "+88",
            "OtherAddrFax": "+88",
            "EmergencyContactNum": "+88",
            "TypOfBuss": "",
            "GenreOfBusiness": "01",
            "Id_type2": "",
            "IrcIssueDt": "01012020",
            "IrcIssuePlace": "000000000000000000000000000000",
            "ErcIssueDt": "01012020",
            "ErcIssuePlace": "000000000000000000000000000000",
            "FeeGroup": "",
            "SmsColectnAcct": "110200002402",
            "SmsRegDate": "22012013"
        },
        "journalinfo": {
            "journalnumber": "4",
            "checkerDate": "04022023"
        }
    };

    const apiResponse = http.post(apiEndpoint, JSON.stringify(postData), { headers: apiHeaders });

    if (apiResponse.status === 202) {
        const responseBody = JSON.parse(apiResponse.body); 
        console.log('Response Message: ' + responseBody);
    }
    else if (apiResponse.status === 400) {
        const responseBody = JSON.parse(apiResponse.body); 
        console.log('Response Message: ' + responseBody.RESPONSE_MESSAGE);
    }
    else {
        console.error('API request failed with status code: ' + apiResponse.body);
    }

    sleep(1); 
}