# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

VAGRANT_BOX         = "generic/centos8s"
VAGRANT_BOX_VERSION = "4.3.4"
CPUS_CENTOS8_NODE    = 2
MEMORY_CENTOS8_NODE  = 4096


Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  # Kubernetes Master Server
  config.vm.define "centos8s" do |node|
  
    node.vm.box               = VAGRANT_BOX
    node.vm.box_check_update  = false
    node.vm.box_version       = VAGRANT_BOX_VERSION
    node.vm.hostname          = "centos8s.eai.com"

    node.vm.network "private_network", ip: "172.16.16.100"
  
    node.vm.provider :virtualbox do |v|
      v.name    = "centos8s"
      v.memory  = MEMORY_CENTOS8_NODE
      v.cpus    = CPUS_CENTOS8_NODE
    end
  
    node.vm.provider :libvirt do |v|
      v.memory  = MEMORY_CENTOS8_NODE
      v.nested  = true
      v.cpus    = CPUS_CENTOS8_NODE
    end
end
end
