# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

VAGRANT_BOX         = "generic/ubuntu2204"
VAGRANT_BOX_VERSION = "4.2.10"
JENKINS_MEMORY = 2048
JENKINS_CPUS = 2
ANSIBLE_MEMORY = 2048
ANSIBLE_CPUS = 2


Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "scripts/bootstrap.sh"

    # Provision Jenkins server
    config.vm.define "jenkins" do |jenkins|
        jenkins.vm.box = VAGRANT_BOX
        jenkins.vm.box_check_update = false
        jenkins.vm.box_version = VAGRANT_BOX_VERSION
        jenkins.vm.hostname = "jenkins.example.com"
      
        jenkins.vm.network "private_network", ip: "172.16.16.200"
      
        jenkins.vm.provider :virtualbox do |v|
          v.name = "jenkins"
          v.memory = JENKINS_MEMORY
          v.cpus = JENKINS_CPUS
        end
      
        jenkins.vm.provider :libvirt do |v|
          v.memory = JENKINS_MEMORY
          v.nested = true
          v.cpus = JENKINS_CPUS
        end
      
        jenkins.vm.provision "shell", path: "scripts/bootstrap_jenkins.sh"
    end
    
end