version: '3'

services:
  nexus:
    user: "200:200"
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
    environment:
      - NEXUS_CONTEXT=/nexus-repo
      - NEXUS_SECURITY_RANDOMPASSWORD=false
    volumes:
      - /mnt/nexus-repo/volumes:/nexus-data