version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - /eai-test-env/redis/redis_data:/data  
    restart: unless-stopped